apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5-deployment
spec:
  selector:
    matchLabels:
      app: yolo5
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: yolo5
    spec:
      containers:
        - name: yolo5
          # image: 854171615125.dkr.ecr.us-east-1.amazonaws.com/deepanshurawat6-detection-model:0.2.0
          image: aryanshrana/yolo5:1.1.1-13
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
          ports:
            - containerPort: 8081
